services:
  larasmart-nginx:
    build:
      context: .docker/nginx
    ports:
      - "8081:8081"
    volumes:
      - "./backend:/var/www/html"
    depends_on:
      - larasmart-fpm
    networks:
      - larasmart-network

  larasmart-fpm:
    build:
      context: .docker/php
    volumes:
      - "./backend:/var/www/html"
    environment:
      - XDG_CONFIG_HOME=/tmp
    depends_on:
      larasmart-mysql:
        condition: service_healthy
    networks:
      - larasmart-network

  larasmart-mysql:
    build:
      context: .docker/mysql
    ports:
      - "3301:3306"
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - larasmart-network

  larasmart-redis:
    build:
      context: .docker/redis
    ports:
      - "6379:6379"
    volumes:
      - redis-storage:/data
    depends_on:
      - larasmart-fpm
    networks:
      - larasmart-network

  larasmart-prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - larasmart-fpm
    networks:
      - larasmart-network

  larasmart-grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - larasmart-prometheus
    networks:
      - larasmart-network

  larasmart-promtail:
    image: grafana/promtail
    build:
      context: .docker/promtail
    volumes:
      - /var/log:/var/log/host
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - larasmart-prometheus
    networks:
      - larasmart-network

  larasmart-loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    depends_on:
      - larasmart-prometheus
    networks:
      - larasmart-network

networks:
  larasmart-network:

volumes:
  grafana-storage:
  redis-storage:
  mysql-storage:
