version: "3.3"

services:
  larasmart-nginx:
    container_name: larasmart-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./backend:/var/www/html"
    depends_on:
      - larasmart-fpm
    networks:
      - larasmart-network

  larasmart-fpm:
    container_name: larasmart-fpm
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - "./backend:/var/www/html"
      - ".docker/php/php.ini:/usr/local/etc/php/php.ini"
    expose:
      - 8003
    environment:
      - XDG_CONFIG_HOME=/tmp
    networks:
      - larasmart-network

  larasmart-mysql:
    container_name: larasmart-mysql
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    ports:
      - "3301:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    volumes:
      - ".docker/mysql/data:/var/lib/mysql"
    networks:
      - larasmart-network

networks:
  larasmart-network: