version: "3.3"

services:
  nginx:
    container_name: service-api-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./backend:/var/www/html"
    depends_on:
      - fpm
    networks:
      - larasmart

  fpm:
    container_name: fpm
    user: "1000:1000"
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - "./backend:/var/www/html"
      - ".docker/php/php.ini:/usr/local/etc/php/php.ini"
    expose:
      - 8003
    environment:
      - XDG_CONFIG_HOME=/tmp
    networks:
      - larasmart

  mysql:
    container_name: mysql
    user: "1000:1000"
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    ports:
      - "3301:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    volumes:
      - ".docker/mysql/data:/var/lib/mysql"
    networks:
      - larasmart

networks:
  larasmart: