global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets: ["localhost:9091"]

  - job_name: 'node'
    static_configs:
      - targets: ["larasmart-node-exporter:9100"]