server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://larasmart-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*.log
  - job_name: host-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: host-logs
          __path__: /var/log/host/*/*.log